/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  'aws_project_region': 'eu-west-1',
  'aws_cognito_identity_pool_id': 'eu-west-1:0a47c44b-6309-42fd-96cc-dd2f68a73e8f',
  'aws_cognito_region': 'eu-west-1',
  'aws_user_pools_id': 'eu-west-1_OYvZBxF0a',
  'aws_user_pools_web_client_id': '2mb6v2sn95mcdsv417gecbk8q3',
  'oauth': {},
  'aws_cognito_username_attributes': ['EMAIL'],
  'aws_cognito_social_providers': [],
  'aws_cognito_signup_attributes': ['EMAIL', 'NAME', 'NICKNAME', 'PHONE_NUMBER'],
  'aws_cognito_mfa_configuration': 'OFF',
  'aws_cognito_mfa_types': ['SMS'],
  'aws_cognito_password_protection_settings': {
    'passwordPolicyMinLength': 8,
    'passwordPolicyCharacters': ['REQUIRES_LOWERCASE', 'REQUIRES_NUMBERS', 'REQUIRES_SYMBOLS', 'REQUIRES_UPPERCASE'],
  },
  'aws_cognito_verification_mechanisms': ['EMAIL'],
  'aws_user_files_s3_bucket': 'hibeats204531-staging',
  'aws_user_files_s3_bucket_region': 'eu-west-1',
  'aws_mobile_analytics_app_id': '780b14347df040aaabcc7809eb9f784d',
  'aws_mobile_analytics_app_region': 'eu-west-1',
};

export default awsmobile;
